/**
 * API endpoint constants. Base path: /api/v1
 * Web and mobile clients must build URLs from this map.
 */
const V1 = '/api/v1';

export const ENDPOINTS = {
  health: {
    live: '/health/live',
    ready: '/health/ready',
  },
  auth: {
    registerShopOwner: `${V1}/auth/register-shop-owner`,
    shopUsers: `${V1}/auth/shop-users`,
    login: `${V1}/auth/login`,
    logout: `${V1}/auth/logout`,
    refresh: `${V1}/auth/refresh`,
    changePassword: `${V1}/auth/change-password`,
    forgotPassword: `${V1}/auth/forgot-password`,
    resetPassword: `${V1}/auth/reset-password`,
    otpRequest: `${V1}/auth/otp/request`,
    otpVerify: `${V1}/auth/otp/verify`,
    emailRequestVerification: `${V1}/auth/email/request-verification`,
    emailVerify: `${V1}/auth/email/verify`,
    smsRequestVerification: `${V1}/auth/sms/request-verification`,
    smsVerify: `${V1}/auth/sms/verify`,
    admins: `${V1}/auth/admins`,
    adminById: (id: string) => `${V1}/auth/admins/${id}`,
    devices: `${V1}/auth/devices`,
    deviceById: (id: string) => `${V1}/auth/devices/${id}`,
    devicesFingerprint: `${V1}/auth/devices/fingerprint`,
    sessions: `${V1}/auth/sessions`,
    profileChangeRequest: `${V1}/auth/profile/change-request`,
    twoFa: {
      status: `${V1}/auth/2fa/status`,
      methods: `${V1}/auth/2fa/methods`,
      authenticatorSetup: `${V1}/auth/2fa/authenticator/setup`,
      authenticatorVerify: `${V1}/auth/2fa/authenticator/verify`,
      backupCodesRegenerate: `${V1}/auth/2fa/backup-codes/regenerate`,
      challengeSend: `${V1}/auth/2fa/challenge/send`,
      challengeVerify: `${V1}/auth/2fa/challenge/verify`,
    },
  },
  shops: {
    base: `${V1}/shops`,
    byId: (id: string) => `${V1}/shops/${id}`,
    switch: `${V1}/shops/switch`,
    members: (id: string) => `${V1}/shops/${id}/members`,
    inviteMember: (id: string) => `${V1}/shops/${id}/members/invite`,
    memberById: (shopId: string, memberId: string) => `${V1}/shops/${shopId}/members/${memberId}`,
  },
  inventory: {
    categories: `${V1}/inventory/categories`,
    categoryById: (id: string) => `${V1}/inventory/categories/${id}`,
    brands: `${V1}/inventory/brands`,
    products: `${V1}/inventory/products`,
    productLookup: `${V1}/inventory/products/lookup`,
    productById: (id: string) => `${V1}/inventory/products/${id}`,
  },
  stock: {
    warehouses: `${V1}/stock/warehouses`,
    warehouseById: (id: string) => `${V1}/stock/warehouses/${id}`,
    in: `${V1}/stock/in`,
    out: `${V1}/stock/out`,
    transfers: `${V1}/stock/transfers`,
    purchaseUpdate: `${V1}/stock/purchase-update`,
    salesDeduction: `${V1}/stock/sales-deduction`,
    levels: `${V1}/stock/levels`,
    movements: `${V1}/stock/movements`,
    lowStockAlerts: `${V1}/stock/alerts/low-stock`,
    outOfStockAlerts: `${V1}/stock/alerts/out-of-stock`,
    expiryAlerts: `${V1}/stock/alerts/expiry`,
    recalculate: `${V1}/stock/recalculate`,
  },
  purchases: {
    base: `${V1}/purchases`,
    byId: (id: string) => `${V1}/purchases/${id}`,
  },
  billing: {
    invoices: `${V1}/billing/invoices`,
    invoiceById: (id: string) => `${V1}/billing/invoices/${id}`,
    invoicePdf: (id: string) => `${V1}/billing/invoices/${id}/pdf`,
    invoiceDownload: (id: string) => `${V1}/billing/invoices/${id}/download`,
    invoiceShare: (id: string) => `${V1}/billing/invoices/${id}/share`,
    invoiceSmsLink: (id: string) => `${V1}/billing/invoices/${id}/sms-link`,
    invoiceWhatsappLink: (id: string) => `${V1}/billing/invoices/${id}/whatsapp-link`,
    sharedInvoice: (token: string) => `${V1}/billing/shared/${token}`,
    payments: `${V1}/billing/payments`,
  },
  customers: {
    base: `${V1}/customers`,
    byId: (id: string) => `${V1}/customers/${id}`,
    duePayments: `${V1}/customers/due-payments`,
    history: (id: string) => `${V1}/customers/${id}/history`,
    purchases: (id: string) => `${V1}/customers/${id}/purchases`,
    ledger: (id: string) => `${V1}/customers/${id}/ledger`,
    reminderSms: (id: string) => `${V1}/customers/${id}/reminders/sms`,
    reminderWhatsapp: (id: string) => `${V1}/customers/${id}/reminders/whatsapp`,
    reminders: (id: string) => `${V1}/customers/${id}/reminders`,
  },
  finance: {
    categories: `${V1}/finance/categories`,
    revenues: `${V1}/finance/revenues`,
    revenueById: (id: string) => `${V1}/finance/revenues/${id}`,
    expenses: `${V1}/finance/expenses`,
    expenseById: (id: string) => `${V1}/finance/expenses/${id}`,
    assets: `${V1}/finance/assets`,
    assetById: (id: string) => `${V1}/finance/assets/${id}`,
    liabilities: `${V1}/finance/liabilities`,
    liabilityById: (id: string) => `${V1}/finance/liabilities/${id}`,
    dashboard: `${V1}/finance/dashboard`,
    cashFlow: `${V1}/finance/cash-flow`,
    profitLoss: `${V1}/finance/profit-loss`,
    revenueAnalysis: `${V1}/finance/revenue-analysis`,
    monthlyReport: `${V1}/finance/reports/monthly`,
    yearlyReport: `${V1}/finance/reports/yearly`,
    taxReport: `${V1}/finance/reports/tax`,
  },
  analytics: {
    dashboard: `${V1}/analytics/dashboard`,
    salesDaily: `${V1}/analytics/sales/daily`,
    salesWeekly: `${V1}/analytics/sales/weekly`,
    salesMonthly: `${V1}/analytics/sales/monthly`,
    topProducts: `${V1}/analytics/top-products`,
    topCustomers: `${V1}/analytics/top-customers`,
    revenueGrowth: `${V1}/analytics/revenue-growth`,
    profitMargin: `${V1}/analytics/profit-margin`,
    inventoryValue: `${V1}/analytics/inventory-value`,
    outstandingPayments: `${V1}/analytics/outstanding-payments`,
    assets: `${V1}/analytics/assets`,
    liabilities: `${V1}/analytics/liabilities`,
  },
  subscriptions: {
    plans: `${V1}/subscriptions/plans`,
    current: `${V1}/subscriptions/current`,
    history: `${V1}/subscriptions/history`,
    limits: `${V1}/subscriptions/limits`,
    feature: (feature: string) => `${V1}/subscriptions/features/${feature}`,
    change: `${V1}/subscriptions/change`,
    cancel: `${V1}/subscriptions/cancel`,
    adminAssign: (shopId: string) => `${V1}/subscriptions/admin/shops/${shopId}/assign`,
  },
  referrals: {
    validate: (code: string) => `${V1}/referrals/validate/${code}`,
    track: `${V1}/referrals/track`,
    dashboard: `${V1}/referrals/dashboard`,
    list: `${V1}/referrals`,
    reward: (id: string) => `${V1}/referrals/${id}/reward`,
    codes: `${V1}/referrals/codes`,
    coupons: `${V1}/referrals/coupons`,
  },
  auditLogs: {
    base: `${V1}/audit-logs`,
    dashboard: `${V1}/audit-logs/dashboard`,
  },
  notifications: {
    base: `${V1}/notifications`,
    markRead: (id: string) => `${V1}/notifications/${id}/read`,
    retry: (id: string) => `${V1}/notifications/${id}/retry`,
  },
  admin: {
    dashboard: `${V1}/admin/dashboard`,
    shops: `${V1}/admin/shops`,
    shopById: (id: string) => `${V1}/admin/shops/${id}`,
    shopSuspend: (id: string) => `${V1}/admin/shops/${id}/suspend`,
    shopBlock: (id: string) => `${V1}/admin/shops/${id}/block`,
    shopActivate: (id: string) => `${V1}/admin/shops/${id}/activate`,
    users: `${V1}/admin/users`,
    userById: (id: string) => `${V1}/admin/users/${id}`,
    userResetPassword: (id: string) => `${V1}/admin/users/${id}/reset-password`,
    subscriptions: `${V1}/admin/subscriptions`,
    subscriptionsAssign: (shopId: string) => `${V1}/admin/subscriptions/shops/${shopId}/assign`,
    approvals: `${V1}/admin/approvals`,
    approvalApprove: (id: string) => `${V1}/admin/approvals/${id}/approve`,
    approvalReject: (id: string) => `${V1}/admin/approvals/${id}/reject`,
    tickets: `${V1}/admin/support/tickets`,
    ticketById: (id: string) => `${V1}/admin/support/tickets/${id}`,
    ticketAssign: (id: string) => `${V1}/admin/support/tickets/${id}/assign`,
    ticketResolve: (id: string) => `${V1}/admin/support/tickets/${id}/resolve`,
    ticketClose: (id: string) => `${V1}/admin/support/tickets/${id}/close`,
    reports: `${V1}/admin/reports`,
    settings: `${V1}/admin/settings`,
    loginHistory: `${V1}/admin/security/login-history`,
    securityDevices: `${V1}/admin/security/devices`,
  },
} as const;

export type Endpoints = typeof ENDPOINTS;
